name: "Gitleaks Action"
description: "A GitHub composite action to install and run Gitleaks"
author: FathAlla Ebrahem
branding:
  icon: aperture
  color: purple
inputs:
  source:
    description: "The source directory to scan for leaks"
    required: false
    default: "."
  output-path:
    description: "Path to Gitleaks report file"
    required: false
    default: "./report"
  report-name:
    description: "Name of the report file"
    required: false
    default: "gitleaks-report.html"
runs:
  using: "composite"
  steps:
    - name: Install Gitleaks
      shell: bash
      run: |
        wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz
        tar -zxvf gitleaks_8.18.4_linux_x64.tar.gz
        sudo mv gitleaks /usr/local/bin/

    - name: Run Gitleaks
      id: gitleaks
      shell: bash
      run: |
        gitleaks detect --source ${{ inputs.source }} --verbose --report-path gitleaks-report.json
      continue-on-error: true

    - name: Check Report
      id: check_report
      shell: bash
      run: |
        if [[ -f gitleaks-report.json && $(cat gitleaks-report.json) == "[]" ]]; then
          echo "No leaks found."
          echo "leaks_found=false" >> $GITHUB_ENV
        else
          echo "Leaks found."
          echo "leaks_found=true" >> $GITHUB_ENV
        fi

    - name: Convert report to HTML
      if: env.leaks_found == 'true'
      shell: bash
      run: |
        HTML_File_Name=${{ inputs.report-name }}
        OUTPUT_PATH=${{ inputs.output-path }}
        mkdir -p $OUTPUT_PATH
        python3 ${{ github.action_path }}/gitleak.py

    - name: Upload report
      if: env.leaks_found == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.report-name }}
        path: ${{ inputs.output-path }}/${{ inputs.report-name }}
        retention-days: 2

